version: '3.3'
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.0.104:3306/root?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend-network
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    networks:
      - backend-network
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - '3306:3306'
volumes:
  data:
networks:
  backend-network:
    driver: bridge